---
format: pdf
fontsize: 11pt
# Custom fonts
mainfont: "Linux Libertine O"
mainfontoptions:
   - "Numbers=Proportional"
#   - "Numbers=OldStyle"
sansfont: "Jost" 
# monofont: "InconsolataGo"
monofontoptions:
  - "Mapping=tex-ansi"
  - "Scale=MatchLowercase"
mathfont: "Libertinus Math"
include-in-header: 
  text: |
    \definecolor{dukeblue}{HTML}{00539B}
    \usepackage[bottom, flushmargin]{footmisc}
    \renewcommand*{\footnotelayout}{\footnotesize}
    \addtolength{\skip\footins}{10pt}    % vertical space between rule and main text
    \setlength{\footnotesep}{5pt}  % vertical space between footnotes

linkcolor: dukeblue
urlcolor: dukeblue
citecolor: dukeblue

geometry:
  - top=0.5in
  - bottom=0.5in
  - left=0.5in
  - right=0.5in
date: "June 14, 2023"
date-format: full
---

```{=tex}
\begin{center}
\Large
\sffamily
The Association of Guideline Directed Prophylaxis with the Incidence of Postoperative Nausea and Vomiting in Pediatric Patients \\
\vspace{0.25cm}
\large
Proposal for A Multicenter Retrospective Observational Cohort Study using the Multicenter Perioperative Outcomes Group (MPOG) Database
\end{center}
```
|                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|----------------|--------------------------------------------------------|
| **Title of Study**       | The Association of Guideline Directed Prophylaxis with the Incidence of Postoperative Nausea and Vomiting in Pediatric Patients: A Multicenter Retrospective Observational Cohort Study                                                                                                                                                                                                                                                                                                                             |
|                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| **Primary Institution**  | Duke University School of Medicine                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| **Primary Author**       | Benjamin Y. Andrew, MD, MHS (Duke)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| **Co-Authors**           | Lucy Everett, MD (MGH); T. Wesley Templeton, MD (Wake Forest); Timothy T. Houle, PhD (MGH); Lisa N. Vitale, MD (Michigan); Vikas O'Reilly-Shah, MD, PhD (U of Washington); Meredith Bailey, MSN, RN (MPOG); Vijay Krishnamoorthy, MD, PhD (Duke); Ashraf Habib, MBBCh, MHS (Duke); Brad Taicher, DO, MBA (Duke)                                                                                                                                                                                                     |
|                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| **Statisticians**        | Benjamin Y. Andrew with support from Timothy T. Houle and Vijay Krishnamoorthy                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| **Type of Study**        | Retrospective, observational                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| **Data Source**          | MPOG database only                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| **IRB Number**           | Duke University Health System IRB (Pro00112464) with Brad Taicher as PI                                                                                                                                                                                                                                                                                                                                                                                                                                             |
|                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| **Aim**                  | Primary aim: estimate the causal effect of compliance with guideline directed PONV prophylaxis (as defined by PONV-04) on the incidence of PONV (as defined by PONV-03) in pediatric patients undergoing general anesthesia.                                                                                                                                                                                                                                                                                        |
|                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| **Number of Patients**   | Data Direct query on 05/11/2023: range from 1,130,173 to 1,546,639 for cohorts with varying exclusions.                                                                                                                                                                                                                                                                                                                                                                                                             |
|                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| **Power Analysis**       | In the setting of our proposed Bayesian outcome models we used a simulation based approach to estimate the effect of sample size on the precision of our estimates. See full text for details - assuming some further exclusion from 1.1 - 1.5 million patients the sample size will be more than sufficient to generate precise effect estimates under our modeling assumptions.                                                                                                                                   |
|                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| **Statistical Approach** | We will use a pseudo-Bayesian propensity score weighting approach whereby we first estimate a multilevel propensity score model and then use overlap and inverse probability of treatment weights generated from this model to estimate the effect of prophylaxis compliance using a Bayesian outcome model for PONV. See full text for modeling details and justification. Several sensitivity analyses are proposed, including alternative modeling approaches and alternative prior distribution specifications. |
|                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| **Resources**            | The primary author will be a clinical fellow in pediatric anesthesiology at Duke beginning August 1, 2023, with one day of dedicated non-clinical time per week.                                                                                                                                                                                                                                                                                                                                                    |

: {tbl-colwidths="\[20, 80\]"}

\small

Last updated: {{< meta date >}}

\footnotesize

Replication materials for this proposal and project are available at: <https://github.com/andrew10043/mpog_peds_ponv>.
